#! /bin/bash
cd /tmp
# Check if any .tgz files exist in /root/
if ls /tmp/*tar.gz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tar.gz; do
    rm -f "$file"
  done
fi

if ls /tmp/*tgz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tgz; do
    rm -f "$file"
  done
fi

if [ -d "/opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin" ]; then
wget https://raw.githubusercontent.com/lovehifi/pico/main/index.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/lib-min.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/mobile.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/mo.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/style.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/Windows-10-Dark.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/background.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/darker.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/desktop.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/addtohomescreen.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/addtohomescreencss.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/js1.tar.gz
wget https://raw.githubusercontent.com/lovehifi/pico/main/js2.tar.gz
AFOL="/tmp/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/material"
BFOL="/opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/"
tar -xzvf /tmp/index.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/lib-min.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/mobile.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/Windows-10-Dark.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/mo.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/style.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/background.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/desktop.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/darker.tar.gz --overwrite -C /tmp/
tar -xzvf /tmp/addtohomescreen.tar.gz --overwrite -C /
tar -xzvf /tmp/addtohomescreencss.tar.gz --overwrite -C /
cp -rf $AFOL $BFOL

hostname=$(hostname)
replacement="http://${hostname}"
if [ -f "/srv/http/assets/js/main.js" ]; then
sed -i "s|https://github.com/rern/rAudio/discussions|${replacement}:9000|g" /srv/http/assets/js/main.js
echo "Completed."
else
echo "File not found. Skipping..."
fi

else
    echo "Please install Material Skin before installing this CSS Mod"
fi


if [ -f "/opt/sq/squeezelite64" ]; then
#sed -i "s|SQ32|SQ64|g" /opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/material/html/js/material.min.js
echo "Completed."
else
echo "Skipping..."
fi

systemctl restart logitechmediaserver-git.service

echo "Installation completed, please clear your browser cache and refresh."
