#! /bin/bash
cd /tmp
# Check if any .tgz files exist in /root/
if ls /tmp/*tar.gz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tar.gz; do
    rm -f "$file"
  done
fi

if ls /tmp/*tgz 1> /dev/null 2>&1; then
  # Remove each .tgz file
  for file in /tmp/*tgz; do
    rm -f "$file"
  done
fi

if [ -d "/opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin" ]; then
wget https://raw.githubusercontent.com/lovehifi/picoreaddon/main/css.tar.gz
wget https://raw.githubusercontent.com/lovehifi/picoreaddon/main/js.tar.gz

AFOL="/tmp/var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/material"
BFOL="/opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/"
tar -xzvf /tmp/css.tar.gz --overwrite -C /
tar -xzvf /tmp/js.tar.gz --overwrite -C /
#cp -rf $AFOL $BFOL

# 15565 this.setLayout(false); to this.setLayout();

hostname=$(hostname)
replacement="http://${hostname}"
if [ -f "/srv/http/assets/js/main.js" ]; then
sed -i "s|https://github.com/rern/rAudio/discussions|http://raudio:9000/|g" /srv/http/assets/js/main.js
echo "Completed."
else
echo "File not found. Skipping..."
fi

else
    echo "Please install Material Skin before installing this CSS Mod"
fi

if [ -f "/opt/sq/squeezelite64" ]; then
#sed -i "s|SQ32|SQ64|g" /opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/material/html/js/material.min.js
echo "Completed."
else
echo "Skipping..."
fi
chown -Rv logitechms:logitechms /opt/logitechmediaserver-git/cache/InstalledPlugins/Plugins/MaterialSkin/HTML/material
systemctl restart logitechmediaserver-git.service

#chown http:http -Rv /opt/logitechmediaserver-git/prefs/material-skin
chown http:http /etc/asound.conf

echo "Installation completed, please clear your browser cache and refresh."
